### ISSUE TITLE
Inject deterministig js regex fails

### ISSUE THREAD

**Issue by bebef1987** [davehunt/raptor-studio#18]
The deteministic js hangs and breaks mitm when recording some sites 

ex: https://yandex.ru/search/?text=barack%20obama&lr=10115

From my research we hit a catastrophic backtracking at line:

https://github.com/mozilla/raptor-studio/blob/4025112d71112acb25766da05d5294c34fe745e4/proxy/scripts/inject_deterministic.py#L133

**Comment by davehunt** [comment]
I believe this code was inspired by WebPageReplay... how does this handle these sites?

**Comment by davehunt** [comment]
Is this still an issue @bebef1987?
