### ISSUE TITLE
add "unpack": true to manifest files

### ISSUE THREAD

**Issue by bebef1987** [davehunt/raptor-studio#23]

**Comment by stephendonner** [comment]
@bebef1987 does https://github.com/mozilla/raptor-studio/blob/75dc77d205305edd068c54326a84f5394896a2fe/studio.py#L199 take care of this?  Looks like this was added in https://github.com/mozilla/raptor-studio/pull/26.

**Comment by bebef1987** [comment]
yes this issue was fixed
